### PR TITLE
[CLIPPER-98] Fixes a race condition in future::when_all

### PR DESCRIPTION
**Pull request by dcrankshaw**
The race condition is documented [here](https://github.com/ucbrise/clipper/pull/56/files#r102356986).

Good find @mwhittaker

### CODE REVIEW

**Comment by shaneknapp** [comment]
test this please

**Comment by dcrankshaw** [comment]
jenkins test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by dcrankshaw** [comment]
@Corey-Zumar Can you review this?

**Review by mwhittaker — APPROVED** [review]
I'd remove the commented out code, but other than that, it looks good to me! :shipit:

**Comment by Corey-Zumar** [comment]
Reviewing...

**Review by Corey-Zumar — APPROVED** [review]
Based on the discussion in #56 , this looks good.

**Pull request merged**
