### PR TITLE
Implement docker_api_utils for DockerContainerManager

### PR DESCRIPTION
**Pull request by withsmilo**
This util helps DockerContainerManager to call Docker API with retry routines.

### CODE REVIEW

**Comment by withsmilo** [comment]
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/2082/ shows,
```
 [unittest_rpc_container] [04:19:57.710][error]    [RPCTEST] Failed to validate containers - test timed out! 
```
I don't know why. Let's try again.

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/2084
```
 [unittests] OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2019-06-10T16:56:49-07:00\\\\\\\" level=fatal msg=\\\\\\\"failed to update store for object type *libnetwork.sbState: timeout\\\\\\\"\\\\n\\\"\"": unknown 
CI_build.Makefile:153: recipe for target 'unittests' failed
make: *** [unittests] Error 1
make: *** Waiting for unfinished jobs....
 [keras36-container] OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"process_linux.go:407: running prestart hook 0 caused \\\"error running hook: exit status 1, stdout: , stderr: time=\\\\\\\"2019-06-10T16:57:49-07:00\\\\\\\" level=fatal msg=\\\\\\\"failed to update store for object type *libnetwork.sbState: timeout\\\\\\\"\\\\n\\\"\"": unknown 
CI_build.Makefile:878: recipe for target 'keras36-container' failed
make: *** [keras36-container] Error 1
```
This is a Docker bug. See https://github.com/docker/for-linux/issues/300.

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by rkooo567** [comment]
The weird thing is that we probably had a similar bug last week (it was also a docker issue we couldn't investigate, but resolved), and it was fixed temporarily for a few days. (one or two days). Should we wait for a few more days to see if it will be fixed again?

**Comment by rkooo567** [comment]
I think @simon-mo is busy lately. I will ping him soon to ask about this.

**Comment by withsmilo** [comment]
@rkooo567 Thanks a lot. We lost last worker now. :sob: 
https://amplab.cs.berkeley.edu/jenkins/job/Clipper-PRB/2085
```
 [integration_py2_fluentd] runtime/cgo: pthread_create failed: Resource temporarily unavailable 
.....
```

**Comment by rkooo567** [comment]
😢 @simon-mo just said he finished submitting his paper today. So I guess he would be back in a few days and bringing updates about worker 2. I think for now, we should disable mxnet test temporarily and use worker 7 and 8 as well. (We also need Simon for this task).

**Comment by simon-mo** [comment]
Hi all,

There are dangling containers left from integration build. I will work on
resolving these

**Review by simon-mo — APPROVED** [review]
this is great. reduce a lot of our boilerplate code

**Pull request merged**
