### PR TITLE
Temporarily Disable Caffe2 Build & Test

### PR DESCRIPTION
**Pull request by simon-mo**
Address #475

### CODE REVIEW

**Comment by goswamig** [comment]
Currently I cant even clone the caffe2 repo :-/

Is there any plan to fix it soon?

**Comment by simon-mo** [comment]
Hi, @gautamkmr 

We chose not to investigate and find a fix for this issue temporarily. I believe you can still install caffe2 via `anaconda`. The pre-built binary should be stable.

**Review by dcrankshaw — APPROVED** [review]

**Review by dcrankshaw — CHANGES_REQUESTED** [review]
Can you throw an exception in the pytorch onnx deployer as well with a link to the issue? That's where this docker image gets used.

**Comment by simon-mo** [comment]
@dcrankshaw A warning may be more suitable? The old containers on dockerhub still works. We just need to re-tag the image for the release. What about a warning saying: the caffe 2 version is not up to date because {link to issue} however you can still use it (we will continue our effort to  maintain it once caffe2 build issue is fixed....)

**Comment by dcrankshaw** [comment]
Yeah that sounds good.

**Comment by simon-mo** [comment]
I just tried pulling the latest pytorch (which contains caffe now), it seems to work.

**Review by dcrankshaw — APPROVED** [review]
lgtm

**Pull request merged**
