### PR TITLE
Fix hard coded checkpoint prefix for TensorFlow deployer.

### PR DESCRIPTION
**Pull request by xunzhang**

### CODE REVIEW

**Comment by simon-mo** [comment]
jenkins test this please

**Review by dcrankshaw — APPROVED** [review]
lgtm

**Comment by dcrankshaw** [comment]
@xunzhang Thanks for the contribution! I'll get this merged as soon as the latest round of tests pass.

**Comment by dcrankshaw** [comment]
jenkins ok to test

**Comment by xunzhang** [comment]
I guess the Jenkins got some errors due to unclean CI environment? Since I also found this error for other RPs. @dcrankshaw Could you please take a look? Thanks.

**Comment by dcrankshaw** [comment]
jenkins test this please

**Pull request merged**
