### PR TITLE
Update Basic example README.md

### PR DESCRIPTION
**Pull request by rkooo567**
_**What kind of change does this PR introduce?**_ 
I fixed basic_example folder's README.md file because it contains deprecated information.

**Does this PR introduce a breaking change?** 
No, I just changed README.md. But probably some explanation that I wrote might be wrong. Please read through one more time to make sure there's no wrong information.

### CODE REVIEW

**Comment by simon-mo** [comment]
jenkins test this please
jenkins add to whitelist

**Comment by simon-mo** [comment]
Jenkins test this please

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
Jenkins test this please

**Comment by simon-mo** [comment]
Jenkins test this please

**Comment by rkooo567** [comment]
Why does it keep failing?

**Comment by simon-mo** [comment]
docker is finicky for some reasons... Let me kick off the retry.

**Comment by simon-mo** [comment]
jenkins test this please

**Pull request merged**
