### PR TITLE
I broke the pip package during rebase

### PR DESCRIPTION
**Pull request by dcrankshaw**
I broke the pip package. @nishadsingh1 can you double check to make sure I fixed it right?

### CODE REVIEW

**Comment by nishadsingh1** [comment]
This LGTM.

The only use of `cur_dir` I'm seeing is in identifing the location of the `check_and_write_deps.py` script. With this PR, that's now happening correctly. Let me know if there are other things to test.

**Review by nishadsingh1 — APPROVED** [review]

**Comment by dcrankshaw** [comment]
Cool. Let me finish testing it again on my end then I'll ping you to merge it.

**Comment by dcrankshaw** [comment]
okay this should be working again

**Comment by dcrankshaw** [comment]
merge when the tests pass

**Comment by dcrankshaw** [comment]
Okay merge this

**Pull request merged**
