### PR TITLE
Rename 'delete_application' to 'unregister_application' in clipper_admin

### PR DESCRIPTION
**Pull request by withsmilo**
* related issue : https://github.com/ucbrise/clipper/issues/603

### CODE REVIEW

**Comment by withsmilo** [comment]
Jenkins ok to test

**Comment by simon-mo** [comment]
@withsmilo can you still create a new method named `delete_application` and call `unregister_application` underneath. So existing code doesn’t need to face this breaking change. 

In delete application, we can even throw a warning saying this api is deprecated and is aliasing unregistered application

**Comment by withsmilo** [comment]
@simon-mo , I understand it. It's great idea! I will refactor this PR as soon as possible.

**Review by rkooo567 — APPROVED** [review]
For me, it is good to go if merge conflict is resolved

**Comment by withsmilo** [comment]
@rkooo567 : I resolved the merge conflict, and added an warning message to the old API(`delete_application`) reflecting @simon-mo 's opnion.

**Comment by withsmilo** [comment]
Jenkins test this please

**Review by rkooo567 — APPROVED** [review]
I think it is good to go. I will just approve because this PR is simple enough. @simon-mo

**Comment by withsmilo** [comment]
@rkooo567 : Thanks! I will merge this if @simon-mo confirms

**Review by simon-mo — APPROVED** [review]

**Comment by withsmilo** [comment]
@simon-mo Thanks! :grinning:

**Pull request merged**
