### PR TITLE
change set_num_replicas in docker_container_manager

### PR DESCRIPTION
**Pull request by Evan-JH-Kim**
Due to 
> [docker_container_manager.py:353] [default-cluster] Found 0 replicas for sample-model:1. Adding 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lineplus/anaconda3/envs/dory_py3.6/lib/python3.6/site-packages/clipper_admin/clipper_admin.py", line 620, in deploy_model
    num_replicas=num_replicas)
  File "/Users/lineplus/anaconda3/envs/dory_py3.6/lib/python3.6/site-packages/clipper_admin/docker/docker_container_manager.py", line 279, in deploy_model
    self.set_num_replicas(name, version, input_type, image, num_replicas)
  File "/Users/lineplus/anaconda3/envs/dory_py3.6/lib/python3.6/site-packages/clipper_admin/docker/docker_container_manager.py", line 363, in set_num_replicas
    self.docker_client.api.inspect_container(name).get("State").get("Health").get("Status") != "healthy":
AttributeError: 'NoneType' object has no attribute 'get'

This error occurs because container.attrs.get("State") and self.docker_client.api.inspect_container(name) can be 'None' type before enough delay time. 
Giving delay time can resolve this problem.

### CODE REVIEW

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by simon-mo** [comment]
Jenkins test this please

**Comment by simon-mo** [comment]
@withsmilo forgot to made you an admin in jenkins, you should be all set now.

**Comment by simon-mo** [comment]
Jenkins ok to test

**Comment by withsmilo** [comment]
@simon-mo : Thanks! but Travis CI are generating error logs now. :(
```
until docker pull clippertesting/query_frontend:993336adf0; do sleep 5; done
until docker pull clippertesting/management_frontend:993336adf0; do sleep 5; done
until docker pull clippertesting/frontend-exporter:993336adf0; do sleep 5; done
until docker pull clippertesting/noop-container:993336adf0; do sleep 5; done
until docker pull clippertesting/python-closure-container:993336adf0; do sleep 5; done
Error response from daemon: manifest for clippertesting/query_frontend:993336adf0 not found
Error response from daemon: manifest for clippertesting/frontend-exporter:993336adf0 not found
Error response from daemon: manifest for clippertesting/python-closure-container:993336adf0 not found
Error response from daemon: manifest for clippertesting/management_frontend:993336adf0 not found
...
```

**Comment by simon-mo** [comment]
@withsmilo yes this is because it's waiting on jenkins to push the images. This is fine because the image built by jenkins will be tagged with the commit hash, we can always go to travis's UI and restart travis build.

**Comment by simon-mo** [comment]
It seems the multi-tenancy tests have failed.

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by simon-mo** [comment]
I believe there's a bug somewhere, this fails the multi-tenancy tests. 

To reproduce it locally, you can `pip install -e .` inside `clipper_admin` directory and run the test with `cd integration_tests; python multi_tenancy_test.py`

**Comment by simon-mo** [comment]
Log
```
19-02-01:05:42:05 INFO [test_utils.py:75] Creating DockerContainerManager
19-02-01:05:42:05 INFO [test_utils.py:94] Starting up Docker cluster multi-tenancy-1-187
19-02-01:05:42:05 INFO [test_utils.py:105] Starting Clipper
19-02-01:05:42:05 INFO [docker_container_manager.py:151] [multi-tenancy-1-187] Starting managed Redis instance in Docker
19-02-01:05:42:12 INFO [docker_container_manager.py:229] [multi-tenancy-1-187] Metric Configuration Saved at /tmp/tmpKMeWmu.yml
19-02-01:05:42:13 INFO [clipper_admin.py:143] [multi-tenancy-1-187] Clipper is running
19-02-01:05:42:14 INFO [test_utils.py:75] Creating DockerContainerManager
19-02-01:05:42:14 INFO [test_utils.py:94] Starting up Docker cluster multi-tenancy-2-6785
19-02-01:05:42:14 INFO [test_utils.py:105] Starting Clipper
19-02-01:05:42:14 INFO [docker_container_manager.py:151] [multi-tenancy-2-6785] Starting managed Redis instance in Docker
19-02-01:05:42:20 INFO [docker_container_manager.py:229] [multi-tenancy-2-6785] Metric Configuration Saved at /tmp/tmp7b6Aa0.yml
19-02-01:05:42:22 INFO [clipper_admin.py:143] [multi-tenancy-2-6785] Clipper is running
19-02-01:05:42:23 INFO [clipper_admin.py:220] [multi-tenancy-1-187] Application testapp0-model was successfully registered
19-02-01:05:42:23 INFO [deployer_utils.py:41] Saving function to /tmp/tmp1cYzDkclipper
19-02-01:05:42:23 INFO [deployer_utils.py:51] Serialized and supplied predict function
19-02-01:05:42:23 INFO [python.py192] Python closure saved
19-02-01:05:42:23 INFO [python.py198] Using Python 2 base image
19-02-01:05:42:23 INFO [clipper_admin.py:472] [multi-tenancy-1-187] Building model Docker image with model data from /tmp/tmp1cYzDkclipper
19-02-01:05:42:24 INFO [clipper_admin.py:477] [multi-tenancy-1-187] Step 1/2 : FROM clippertesting/python-closure-container:2e57b899a3
19-02-01:05:42:24 INFO [clipper_admin.py:477] [multi-tenancy-1-187] ---> ac6d18edda4e
19-02-01:05:42:24 INFO [clipper_admin.py:477] [multi-tenancy-1-187] Step 2/2 : COPY /tmp/tmp1cYzDkclipper /model/
19-02-01:05:42:24 INFO [clipper_admin.py:477] [multi-tenancy-1-187] ---> 1b3f714b6bef
19-02-01:05:42:24 INFO [clipper_admin.py:477] [multi-tenancy-1-187] Successfully built 1b3f714b6bef
19-02-01:05:42:24 INFO [clipper_admin.py:477] [multi-tenancy-1-187] Successfully tagged multi-tenancy-1-187-testapp0-model:1
19-02-01:05:42:24 INFO [clipper_admin.py:479] [multi-tenancy-1-187] Pushing model Docker image to multi-tenancy-1-187-testapp0-model:1
19-02-01:05:43:05 INFO [docker_container_manager.py:353] [multi-tenancy-1-187] Found 0 replicas for testapp0-model:1. Adding 1
19-02-01:05:43:07 INFO [clipper_admin.py:656] [multi-tenancy-1-187] Successfully registered model testapp0-model:1
19-02-01:05:43:07 INFO [clipper_admin.py:574] [multi-tenancy-1-187] Done deploying model testapp0-model:1.
19-02-01:05:43:07 INFO [clipper_admin.py:282] [multi-tenancy-1-187] Model testapp0-model is now linked to application testapp0-model
19-02-01:05:43:07 INFO [clipper_admin.py:220] [multi-tenancy-2-6785] Application testapp0-model was successfully registered
19-02-01:05:43:07 INFO [deployer_utils.py:41] Saving function to /tmp/tmp5Vw8wMclipper
19-02-01:05:43:07 INFO [deployer_utils.py:51] Serialized and supplied predict function
19-02-01:05:43:07 INFO [python.py192] Python closure saved
19-02-01:05:43:07 INFO [python.py198] Using Python 2 base image
19-02-01:05:43:07 INFO [clipper_admin.py:472] [multi-tenancy-2-6785] Building model Docker image with model data from /tmp/tmp5Vw8wMclipper
19-02-01:05:43:08 INFO [clipper_admin.py:477] [multi-tenancy-2-6785] Step 1/2 : FROM clippertesting/python-closure-container:2e57b899a3
19-02-01:05:43:08 INFO [clipper_admin.py:477] [multi-tenancy-2-6785] ---> ac6d18edda4e
19-02-01:05:43:08 INFO [clipper_admin.py:477] [multi-tenancy-2-6785] Step 2/2 : COPY /tmp/tmp5Vw8wMclipper /model/
19-02-01:05:43:08 INFO [clipper_admin.py:477] [multi-tenancy-2-6785] ---> a17bd6c1aad9
19-02-01:05:43:08 INFO [clipper_admin.py:477] [multi-tenancy-2-6785] Successfully built a17bd6c1aad9
19-02-01:05:43:08 INFO [clipper_admin.py:477] [multi-tenancy-2-6785] Successfully tagged multi-tenancy-2-6785-testapp0-model:1
19-02-01:05:43:08 INFO [clipper_admin.py:479] [multi-tenancy-2-6785] Pushing model Docker image to multi-tenancy-2-6785-testapp0-model:1
19-02-01:05:43:55 INFO [docker_container_manager.py:353] [multi-tenancy-2-6785] Found 0 replicas for testapp0-model:1. Adding 1
19-02-01:05:44:00 INFO [clipper_admin.py:656] [multi-tenancy-2-6785] Successfully registered model testapp0-model:1
19-02-01:05:44:00 INFO [clipper_admin.py:574] [multi-tenancy-2-6785] Done deploying model testapp0-model:1.
19-02-01:05:44:00 INFO [clipper_admin.py:282] [multi-tenancy-2-6785] Model testapp0-model is now linked to application testapp0-model

'{"query_id":0,"output":0.6000000000000001,"default":false}', 5.698000 ms
'{"query_id":0,"output":"None","default":true,"default_explanation":"No connected models found for query"}', 8.068000 ms
```

```pytb

Traceback (most recent call last):
File "/clipper/integration-tests/multi_tenancy_test.py", line 78, in test(kubernetes=False)
File "/clipper/integration-tests/multi_tenancy_test.py", line 24, in test
	assert not res_2['default']
AssertionError
```

**Comment by withsmilo** [comment]
@simon-mo : 
Thank you for your kindness. After several tests, I noticed that the multi-tenancy test was too unstable. 
To solve this problem, we need to add `time.sleep(10)` as shown in the codes below. Do I need to make a PR to fix it?

https://github.com/ucbrise/clipper/blob/develop/integration-tests/multi_tenancy_test.py#L14-L27

```python
def test(kubernetes):
    conn_1 = create('multi-tenancy-1-{}'.format(randint(1,9999)), use_kubernetes=kubernetes)
    conn_2 = create('multi-tenancy-2-{}'.format(randint(1,9999)), use_kubernetes=kubernetes)

    deploy_(conn_1, use_kubernetes=kubernetes)
    deploy_(conn_2, use_kubernetes=kubernetes)

    time.sleep(10)  # <---- added!

    res_1 = predict_(conn_1.get_query_addr(), [.1, .2, .3])
    res_2 = predict_(conn_2.get_query_addr(), [.1, .2, .3])
    assert not res_1['default']
    assert not res_2['default']

    conn_1.stop_all()
    conn_2.stop_all()
```

**Comment by simon-mo** [comment]
Fix added at https://github.com/ucbrise/clipper/pull/626, will rebase after that.

**Comment by withsmilo** [comment]
@Evan-JH-Kim , please merge this PR with latest `develop` branch.

**Comment by withsmilo** [comment]
Jenkins ok to test

**Comment by Evan-JH-Kim** [comment]
Travis CI still fails.. what's wrong with it?

**Comment by withsmilo** [comment]
@Evan-JH-Kim : Passed on all tests of Travis CI.
@simon-mo : Please review this PR.

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
