### PR TITLE
[CI] Add retry-routine to 'docker push' in clipper_docker.cfg.py

### PR DESCRIPTION
**Pull request by withsmilo**
* This patch is needed to retry if 'docker push' fails.
* related issue : no.2 in https://github.com/ucbrise/clipper/issues/656.

### CODE REVIEW

**Comment by withsmilo** [comment]
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1827 shows the following two errors.
```
 [unittest_libclipper] [ RUN      ] TimerSystemTests.SingleTimerExpire 
 [unittest_libclipper] /clipper/src/libclipper/test/timers_test.cpp:29: Failure 
 [unittest_libclipper] Value of: timer_future.isReady() 
 [unittest_libclipper] Actual: false 
 [unittest_libclipper] Expected: true 
 [unittest_libclipper] Uh oh 
 [unittest_libclipper] [  FAILED  ] TimerSystemTests.SingleTimerExpire (1 ms) 

 [unittest_libclipper] [ RUN      ] TimerSystemTests.OutOfOrderTimerExpire 
 [unittest_libclipper] /clipper/src/libclipper/test/timers_test.cpp:61: Failure 
 [unittest_libclipper] Value of: t2.isReady() 
 [unittest_libclipper] Actual: false 
 [unittest_libclipper] Expected: true 
 [unittest_libclipper] [  FAILED  ] TimerSystemTests.OutOfOrderTimerExpire (0 ms) 
```
Hmm, I don't know why the errors occurred. Let's execute Jenkins job again.

**Comment by withsmilo** [comment]
jenkins test this please

**Comment by withsmilo** [comment]
@simon-mo , I found a collision between `run_rpc_container_tests` and `run_frontend_tests` in https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1829/.
```
[unittest_frontend] [15:20:50.440][error]      [REDIS] Error with command "GET CURRENT_MODEL_VERSION:m": 
 [unittest_frontend] [15:20:50.441][error]      [REDIS] No versions found for model m 
 [unittest_frontend] [15:20:50.441][error] [QUERYFR...] Found model m with missing current version. 
 [unittest_frontend] [15:20:50.515][info]         [RPC] Found message to receive 
 [unittest_frontend] [15:20:50.515][info]         [RPC] Found message to receive 
 [unittest_frontend] [15:20:50.515][info]         [RPC] New container connected 
 [unittest_frontend] [15:20:50.515][info]         [RPC] Container added 
 [unittest_frontend] [15:20:50.516][info]       [REDIS] Successfully issued command "SELECT 3" 
 [unittest_frontend] [15:20:50.517][info]       [REDIS] MESSAGE: hset 
 [unittest_frontend] [15:20:50.517][info]       [REDIS] Successfully issued command "HMSET rpctest_py,1,0 model_id rpctest_py:1 model_name rpctest_py model_version 1 model_replica_id 0 zmq_connection_id 0 batch_size 1 input_type doubles" 
 [unittest_frontend] [15:20:50.517][info]  [THREADPOOL] Work queue created for model rpctest_py:1, replica 0 
 [unittest_frontend] [15:20:50.517][info]       [REDIS] Successfully issued command "SELECT 3" 
 [unittest_frontend] [15:20:50.517][info]       [REDIS] Successfully issued command "HGETALL rpctest_py,1,0" 
```

**Comment by withsmilo** [comment]
jenkins test this please

**Comment by RehanSD** [comment]
Jenkins test this please.

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
