### PR TITLE
Fix a bug that ManagementFrontend adds a garbage to http response

### PR DESCRIPTION
**Pull request by withsmilo**
Currently ManagementFrontend sends `['http header' + 'content' + '\n']` as a http response to the outer side. Our team found some error cases occurred by wrong value(content.length()) of Content-Length in the 'http header'. To fix it, `\n` must be removed from the http response.

I found the same bug in QueryFrontend and pull-requested it already. (#415)

### CODE REVIEW

**Comment by jvdmeulen92** [comment]
jenkins test this please

**Comment by simon-mo** [comment]
Jenkins ok to test

**Comment by simon-mo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
@simon-mo : 
Why did [first Jenkins job](https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1778/
) fail? Anyway, this pull request has finally passed Jenkins. Please merge this.

**Review by simon-mo — APPROVED** [review]
lgtm

**Comment by simon-mo** [comment]
@withsmilo thanks, i just rebased it, I will merge this once the test passes again. I understand the tests are still flaky. I will take care of it.

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
Jenkins test this please

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
