### PR TITLE
Use default java.library.path instead of reading from JZMQ_HOME env variable

### PR DESCRIPTION
**Pull request by dcrankshaw**
cc @shaneknapp

### CODE REVIEW

**Comment by shaneknapp** [comment]
this is for testing https://github.com/ucbrise/jenkins-infra/pull/54

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
ok, it didn't complain about not finding jzmq, but still failed.  the error is:

```
[ RUN      ] WhenEitherTests.EntryAlreadyComplete
/home/jenkins/workspace/Clipper-PRB/src/libclipper/test/future_test.cpp:200: Failure
Value of: completion_future.is_ready()
  Actual: false
Expected: true
[  FAILED  ] WhenEitherTests.EntryAlreadyComplete (8 ms)
```

**Comment by shaneknapp** [comment]
Test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by dcrankshaw** [comment]
jenkins test this please

**Comment by dcrankshaw** [comment]
Tests failed with a JZMQ error so our current solution isn't working. I don't really have time to dig into this right now, can we leave the current JZMQ solution in place?

```
Starting java RPC test container...
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jzmq in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.zeromq.ZMQ.<clinit>(ZMQ.java:40)
	at ai.clipper.rpc.RPC.start(RPC.java:42)
	at ai.clipper.rpctest.RPCProtocolTest.main(RPCProtocolTest.java:15)
```

**Comment by shaneknapp** [comment]
just to recap our IRL conversation:

let's leave this PR open for now, and we can revisit this when we have
time.  i haven't changed the workers, so everything else should be totally
fine.

**Pull request closed without merging**
