### PR TITLE
fixed bug in querying for specific versions

### PR DESCRIPTION
**Pull request by dcrankshaw**
@simon-mo can you merge this once the tests pass, in case I'm out of town already?

### CODE REVIEW

**Comment by simon-mo** [comment]
jenkins rest this please

**Comment by simon-mo** [comment]
jenkins test this please

**Comment by simon-mo** [comment]
jenkins test this please

**Review by simon-mo — APPROVED** [review]
lgtm

**Comment by dcrankshaw** [comment]
jenkins test this please

**Pull request merged**
