### PR TITLE
Fix some bugs of PySpark integration test & Disable Spark UI

### PR DESCRIPTION
**Pull request by withsmilo**
* related issue : no.9 in https://github.com/ucbrise/clipper/issues/656

### CODE REVIEW

**Comment by simon-mo** [comment]
@withsmilo I’m thinking we should also disable spark UI. The reason our Jenkins might be failing because Apache spark integration test is primarily using our Jenkins cluster. That explains all the port conflicts. We can do it via `SparkSession.builder.config(“spark.ui.enabled”, “false”)...` 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by withsmilo** [comment]
@simon-mo , I agreed. I will push an additional commit related with your suggestion to this PR.

**Comment by withsmilo** [comment]
@simon-mo , please review [this commit](https://github.com/ucbrise/clipper/pull/665/commits/f115c9a0cffd8156bfdbb74c18e86c5dba9b6910).

**Review by simon-mo — APPROVED** [review]

**Comment by rkooo567** [comment]
Is it okay that it fails the CI after the merge?

**Comment by withsmilo** [comment]
@rkooo567 : yes, the CI system is more stable than previous.

**Pull request merged**
