### PR TITLE
[CLIPPER-126] Remove application command

### PR DESCRIPTION
**Pull request by nishadsingh1**
https://clipper.atlassian.net/projects/CLIPPER/issues/CLIPPER-126?filter=allopenissues

Endpoint, handler, tests, and management library function added for deleting apps.

We could use a 204 http response instead of a 200 when we successfully delete, but then we wouldn't be able to send a "Success!" message in the response.

### CODE REVIEW

**Comment by dcrankshaw** [comment]
jenkins test this please

**Review by dcrankshaw — CHANGES_REQUESTED** [review]
This will delete an application from Redis, but it won't actually delete it from the Clipper query processor.

Add an else if statement to the query frontend [here](https://github.com/ucbrise/clipper/blob/bac5ec8b8242fc622b69abe6d9c4581cfdc1cbe8/src/frontends/src/query_frontend.hpp#L109-L123):

```
else if (event_type == "del") {
  std::string name = key;
  delete_application(name);
}
```
Where `delete_application()` deletes the 2 endpoints added [here](https://github.com/ucbrise/clipper/blob/bac5ec8b8242fc622b69abe6d9c4581cfdc1cbe8/src/frontends/src/query_frontend.hpp#L162) and [here](https://github.com/ucbrise/clipper/blob/bac5ec8b8242fc622b69abe6d9c4581cfdc1cbe8/src/frontends/src/query_frontend.hpp#L188).

You'll need to modify `server_http.hpp` as well to add a `delete_endpoint()` method. Look at the [`add_endpoint`](https://github.com/ucbrise/clipper/blob/develop/src/libs/httpserver/server_http.hpp#L271-L293) code to see how endpoints are added. Basically do the same thing but in reverse.

**Comment by nishadsingh1** [comment]
This isn't working yet -- `delete_endpoint` in server_http isn't actually decreasing the number of endpoints. Just pushed to the branch as a progress update

**Comment by dcrankshaw** [comment]
jenkins ok to test

**Comment by nishadsingh1** [comment]
If we run `QueryFrontendTest.TestDeleteApplication` (without the asserts in `server_http.hpp`'s `delete_endpoint`), `EXPECT_EQ(no_apps, rh_.num_applications())` fails because `rh_.num_applications()` is 1 (and `no_apps` is 0). `r_.num_applications()` relies on `server_http.num_endpoints()`. That `rh_.num_applications()` is still 1 after a call to `delete_endpoint` suggests that no endpoint was deleted.

In the latest commit I made asserts in `server_http.hpp`'s `delete_endpoint` that isolate the scope of that problem to just the code in `delete_endpoint`. Do you mind taking a look at them?

**Comment by rmdort** [comment]
Is this ready for merge? @nishadsingh1

**Comment by nishadsingh1** [comment]
This gets more complicated with #226 and isn't working in it's current state. Closing

**Pull request closed without merging**
