### PR TITLE
Fix Bug with Deployment of SparkML Models

### PR DESCRIPTION
**Pull request by santi81**
Currently its only possible to deploy Spark ml pipelines or Spark mllib Models.There is no support to deploy Spark ml models.

### CODE REVIEW

**Comment by dcrankshaw** [comment]
jenkins ok to test

**Review by dcrankshaw — APPROVED** [review]
LGTM. Will merge once the tests pass.

**Comment by santi81** [comment]
@dcrankshaw the build errors seem unrelated to the changes I made. Kubernetes integration tests are failing, could have been something sporadic.Could you please re-trigger the build?

**Comment by dcrankshaw** [comment]
jenkins test this please

**Pull request merged**
