### PR TITLE
fixed decoding error when when parsing graph_def from string.

### LINKED ISSUE #376: GraphDef ParseFromString error
When loading a tensorflow pb model, the following error happens:
 File "/container/tf_container.py", line 29, in __init__
    graph_def.ParseFromString(f.read())
 google.protobuf.message.DecodeError: Error parsing message

Why does it happens?

### PR DESCRIPTION
**Pull request by yrbahn**
https://stackoverflow.com/questions/46547319/error-when-parsing-graph-def-from-string

Fixes #376

### CODE REVIEW

**Comment by simon-mo** [comment]
Jenkins ok to test

**Comment by simon-mo** [comment]
There are some formatting to issue. Can you run `bin/format_code.sh` according to http://clipper.ai/contributing/ ?

**Comment by yrbahn** [comment]
I have checked code format!

**Comment by yrbahn** [comment]
I have deleted some file committed by mistake

**Comment by simon-mo** [comment]
@dcrankshaw @Corey-Zumar Can you take a look and merge if it's good to go? This fixes #376

**Review by dcrankshaw — APPROVED** [review]
LGTM. This cleans up the tensorflow deployer tests nicely.

**Pull request merged**
