### PR TITLE
R model serialization fixes

### LINKED ISSUE #396: Dependency issues while building R model
While deploying a trained randomForest model in R, I come across the following error:
`Error in .local(e, collector, basedir, reset, formulaInputs, ...) : 
  don't know about randomForest.formularandomForest
`

Steps to reproduce:
Train a randomForest classifier on a sample data
```
library(randomForest)
input_data <- read.csv('sample.csv')
model <- randomForest(churn~., data = input_data, keep.forest=TRUE)
```
Wrap the model in a function
```
model_wrap <- function(input){
  output <- predict(model, input)
  return(output)
}
```
Build the model
```
Rclipper::build_model("test-model", "1", model_wrap, sample_input = input_data[1,])
```
Above step throws the error
```
Error in .local(e, collector, basedir, reset, formulaInputs, ...) : 
  don't know about randomForest.formularandomForest
```

### PR DESCRIPTION
**Pull request by Corey-Zumar**
Fixes #396 

* CodeDepends is a library for finding R function and object dependencies using static expression analysis. Therefore, the previous use of the library in Rclipper was incorrect; it invoked CodeDepends on function/object names rather than their associated definitions.

* To fix this issue, we leverage the [histry package](https://cran.r-project.org/web/packages/histry/index.html) to map object / function names to definitions in an interactive session history. We then use CodeDepends to correctly analyze these defining expressions.

### CODE REVIEW

**Review by dcrankshaw — APPROVED** [review]
lgtm. Will merge once tests pass.

**Comment by dcrankshaw** [comment]
@Corey-Zumar the tests are failing with the following error:
```
localhost:41560
* installing to library '/usr/local/lib/R/site-library'
ERROR: dependency 'histry' is not available for package 'Rclipper'
* removing '/usr/local/lib/R/site-library/Rclipper'
Exiting unit tests...
```

**Comment by Corey-Zumar** [comment]
@dcrankshaw Added a line to install the histry package when building the container; that should fix the issue

**Comment by Corey-Zumar** [comment]
jenkins test this please

**Pull request merged**
