### PR TITLE
Remove metric log from query frontend

### PR DESCRIPTION
**Pull request by simon-mo**

### CODE REVIEW

**Comment by withsmilo** [comment]
@simon-mo , may I review this PR?

**Comment by simon-mo** [comment]
Yes please. You can merge it if it looks good to you.

**Review by withsmilo — APPROVED** [review]
LGTM!

**Comment by withsmilo** [comment]
@simon-mo , please merge this PR because I don't have the merge permission. To be honest, our team has already applied this. :)

**Pull request merged**
