### PR TITLE
Fix 100% CPU utilization issue [V2]

### PR DESCRIPTION
**Pull request by simon-mo**
https://github.com/ucbrise/clipper/pull/581

Applied patch here: https://github.com/ucbrise/clipper/pull/581#issuecomment-439426276

### CODE REVIEW

**Comment by simon-mo** [comment]
@withsmilo should we merge this for now? does it come with a performance penalty?

**Comment by withsmilo** [comment]
No! I found a new bug after merging with this PR for test. I will try to fix it in a few days.

**Comment by withsmilo** [comment]
@simon-mo : I did not reproduce the bug. Maybe I've mistaken it before. Let's merge this PR. :)

**Comment by RehanSD** [comment]
Simon do you want me to add my review and merge this?

**Review by RehanSD — APPROVED** [review]
Looks good, and Sungjun didn't seem to be able to replicate his error so lgtm

**Pull request merged**
