### PR TITLE
Implement delete_versioned_model API

### PR DESCRIPTION
**Pull request by withsmilo**
### 1. in brief
* related issue : https://github.com/ucbrise/clipper/issues/603
* Remove the specified versions of the specified models from Clipper internal.

### 2. TODO
* [x] Implement `unregister_versioned_models` Clipper API in clipper_admin
* [x] Implement `delete_versioned_model` Management-Frontend API
* [x] Add some test cases to integration-tests/clipper_admin_tests.py
* [x] Add some test cases to src/management/src/management_frontend_tests.cpp

#### Description
Unregister the specified versions of the specified models from Clipper internal.
This function does not be opened to public because it might cause critical operation.
Please use `stop_models`, `stop_versioned_models`, `stop_inactive_model_versions`, and `stop_all_model_containers` APIs according to your need.

### CODE REVIEW

**Comment by avinregmi** [comment]
Hey guys, I'm not getting the changes when installed using pip. Has this not been pushed in master yet?

**Comment by withsmilo** [comment]
@avinregmi : This pull request was NOT merged with `develop` branch yet. After fixing unstable CI infra, I will try to merge this.

**Comment by withsmilo** [comment]
jenkins test this please

**Comment by withsmilo** [comment]
Jenkins ok to test

**Comment by withsmilo** [comment]
jenkins test this please

**Comment by withsmilo** [comment]
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1824 shows the following error.
```
 [publish_tf36-container] Head https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/dd/dde37b0b47901bfc6be0c2857a4e9a757175ad82246ed224bd405a02f7f0e020/data?verify=1553522760-379DR9XVMPr%2FkUMzi9C2M5iBO6I%3D: net/http: TLS handshake timeout 
CI_build.Makefile:626: recipe for target 'publish_tf36-container' failed
make: *** [publish_tf36-container] Error 1
make: *** Waiting for unfinished jobs....
```
This error occurred because `docker push` failed. I will add retry-routine to `docker push` in clipper_docker.cfg.py.

**Comment by withsmilo** [comment]
jenkins test this please

**Review by simon-mo — DISMISSED** [review]

**Comment by withsmilo** [comment]
The latest Jenkins job shows me that the TaskExecutor has some bugs. I will try to debug it tonight.

**Comment by withsmilo** [comment]
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/1943/ shows this error. I will try to fix this bug.
```
[integration_py2_admin_unit_test] ====================================================================== 
 [integration_py2_admin_unit_test] FAIL: test_remove_inactive_container (__main__.ClipperManagerTestCaseLong) 
 [integration_py2_admin_unit_test] ---------------------------------------------------------------------- 
 [integration_py2_admin_unit_test] Traceback (most recent call last): 
 [integration_py2_admin_unit_test] File "/clipper/integration-tests/clipper_admin_tests.py", line 864, in test_remove_inactive_container 
 [integration_py2_admin_unit_test] "No connected models found for query") 
 [integration_py2_admin_unit_test] AssertionError: u'Failed to retrieve a prediction response within the specified latency SLO' != 'No connected models found for query' 
```

**Comment by withsmilo** [comment]
jenkins test this please

**Comment by withsmilo** [comment]
jenkins test this please

**Comment by rkooo567** [comment]
Can we add a unittest to `management_frontend_tests.cpp`?

**Comment by withsmilo** [comment]
@rkooo567 , sure. I will.

**Comment by withsmilo** [comment]
https://amplab.cs.berkeley.edu/jenkins//job/Clipper-PRB/2012/ shows,
```
 [py35-rpc]   ERROR: Complete output from command /usr/local/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-mv0jvuu_/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-4xpgl5lj --python-tag cp35: 
 [py35-rpc]   ERROR: /usr/local/lib/python3.5/site-packages/setuptools/dist.py:407: UserWarning: The version specified ('e70f089044') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details. 
...
 [py35-rpc] creating build/bdist.linux-x86_64/wheel/clipper_admin-e70f089044.dist-info/WHEEL 
 [py35-rpc] Traceback (most recent call last): 
 [py35-rpc] File "<string>", line 1, in <module> 
 [py35-rpc] File "/tmp/pip-req-build-mv0jvuu_/setup.py", line 33, in <module> 
 [py35-rpc] 'TensorFlow': ['tensorflow'], 
 [py35-rpc] File "/usr/local/lib/python3.5/site-packages/setuptools/__init__.py", line 140, in setup 
 [py35-rpc] return distutils.core.setup(**attrs) 
 [py35-rpc] File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup 
 [py35-rpc] dist.run_commands() 
 [py35-rpc] File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands 
 [py35-rpc] self.run_command(cmd) 
 [py35-rpc] File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command 
 [py35-rpc] cmd_obj.run() 
 [py35-rpc] File "/usr/local/lib/python3.5/site-packages/wheel/bdist_wheel.py", line 246, in run 
 [py35-rpc] with WheelFile(wheel_path, 'w') as wf: 
 [py35-rpc] File "/usr/local/lib/python3.5/site-packages/wheel/wheelfile.py", line 40, in __init__ 
 [py35-rpc] raise WheelError("Bad wheel filename {!r}".format(basename)) 
 [py35-rpc] wheel.cli.WheelError: Bad wheel filename 'clipper_admin-e70f089044-py2.py3-none-any.whl' 
 [py35-rpc] ---------------------------------------- 
 [py35-rpc]   ERROR: Failed building wheel for clipper-admin 
```
```
 [integration_py2_mxnet] Sleep 65 secs before starting a test 
 [integration_py2_mxnet] Starting Trial 0 with timeout 2400.0 seconds 
 [integration_py2_mxnet] Sleep 95 
 [integration_py2_mxnet] Starting Trial 1 with timeout 2400.0 seconds 
 [integration_py2_mxnet] Sleep 127 
 [integration_py2_mxnet] All retry failed. 
CI_test.Makefile:152: recipe for target 'integration_py2_mxnet' failed
make: *** [integration_py2_mxnet] Error 1
```

**Comment by withsmilo** [comment]
jenkins test this please

**Comment by rkooo567** [comment]
@withsmilo Will review once the last test is added! I am a little busy this week.

**Review by simon-mo — APPROVED** [review]
@withsmilo great work! thank you for implementing this. This is the missing piece in the Clipper API

**Pull request merged**
