### PR TITLE
Fix empty vector problem in reddis.cpp

### PR DESCRIPTION
**Pull request by lucasmoura**
This MR address the following issue #77, which if an empty vector is received, it will look at an invalid position of this vector.

To deal with that, this MR checks if the received vector is empty, and if it is, it returns an empty string. Also, tests were created for both of the functions were this behavior occur.

### CODE REVIEW

**Comment by dcrankshaw** [comment]
jenkins test this please

**Comment by lucasmoura** [comment]
@dcrankshaw I believe the code is in the right format now

**Comment by dcrankshaw** [comment]
jenkins test this please

**Review by dcrankshaw — APPROVED** [review]
LGTM

**Pull request merged**
