### PR TITLE
Adds support for custom ssh ports to clipper_manager library

### PR DESCRIPTION
**Pull request by dcrankshaw**
As requested by #90.

@nishadsingh1 Want to tackle this as your first code review? Should be pretty simple but you should test it to make sure it works. You don't have permissions to approve pull requests yet, so I added @Corey-Zumar as a reviewer as well.

### CODE REVIEW

**Comment by nishadsingh1** [comment]
Happy to take a look at this. Can you provide a remote machine I could use that has docker/docker-compose installed that I could test this on?

**Comment by nishadsingh1** [comment]
This works! Deploying clipper locally, remotely using the default ssh port (22) without specifying it, and on a user-specified port (not necessary default) all work.

It seems like the only things that should be added is documentation about these changes. The tutorial comes to mind: in tutorial_part_one, when explaining how to connect locally or remotely, we should provide updated instructions on how to use the interface since it has changed from `clipper_manager.Clipper(host, user=None, key_path=None)` to `clipper_manager.Clipper(host, ssh_port=22, user=None, key_path=None)`.

There may be other docs to update (not sure).

**Comment by dcrankshaw** [comment]
Added documentation about using a custom SSH port to the tutorial. It's also documented in the the pydoc comment in `clipper_manager.py` which we will host as API documentation before the release.

**Comment by dcrankshaw** [comment]
@Corey-Zumar: Nishad has tested this PR but he doesn't have permissions to approve the request. Can you take a quick look and if it looks okay merge it?

**Comment by dcrankshaw** [comment]
@Corey-Zumar Can you merge this?

**Review by Corey-Zumar — APPROVED** [review]
LGTM

**Pull request merged**
