### PR TITLE
Fix a bug that a new model replica couldn't be registerd with the Clipper's RPCService

### PR DESCRIPTION
**Pull request by withsmilo**
* related issue : https://github.com/ucbrise/clipper/issues/636

### CODE REVIEW

**Comment by rkooo567** [comment]
LGTM!

**Comment by withsmilo** [comment]
jenkins test this please

**Comment by withsmilo** [comment]
@rkooo567 : Thank you! Don't you have the permission to review?

**Review by simon-mo — APPROVED** [review]

**Comment by simon-mo** [comment]
@withsmilo thanks for the patch! @rkooo567 i just gave you access to review and merge PR.

**Pull request merged**
