### PR TITLE
fixed backslash escape issue for removing remote containers

### LINKED ISSUE #209: Remove inactive container Error 64
Getting this error when `remove_inactive_containers` is called
````
Fatal error: run() received nonzero return code 64 while executing!

Requested: docker inspect --format "{{ index .Config.Labels \"ai.clipper.model_container.model_version\"}}" 1935bd17d02b
Executed: /bin/bash -l -c "docker inspect --format \"{{ index .Config.Labels \\"ai.clipper.model_container.model_version\\"}}\" 1935bd17d02b"

Template parsing error: template: :1: unexpected "\\" in operand
````

### PR DESCRIPTION
**Pull request by dcrankshaw**
Fixes #209

### CODE REVIEW

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by shaneknapp** [comment]
test this please

**Comment by dcrankshaw** [comment]
@nishadsingh1 can you review this?

**Comment by nishadsingh1** [comment]
Yep looking at it now

**Review by nishadsingh1 — APPROVED** [review]
LGTM!

**Comment by dcrankshaw** [comment]
jenkins test this please

**Pull request merged**
