### PR TITLE
Expose http configurations to clipper_admin

### PR DESCRIPTION
**Pull request by withsmilo**
* solved: https://github.com/ucbrise/clipper/issues/523
* exposed configurations
  * qf_http_thread_pool_size
    * int(optional)
    * The size of thread pool created in query frontend for http serving.
  * qf_http_timeout_request
    * int(optional)
    * The seconds of timeout on request handling in query frontend for http serving.
  * qf_http_timeout_content
    * int(optional)
    * The seconds of timeout on content handling in query frontend for http serving.

### CODE REVIEW

**Comment by simon-mo** [comment]
@withsmilo Thanks for the PR. These changes are great.

I think we should expose these parameters but directly expose them at `start_clipper` seems to be too much. 

Maybe in start_clipper, we can add an option field instead of three separate arguments:
```
     qf_options: (dict) extra configuration parameters for query frontend
```

My main concern is simply the usability and simplicity of our python API. 

@dcrankshaw What's your thought on this?

**Comment by simon-mo** [comment]
jenkins test this please

**Comment by withsmilo** [comment]
@simon-mo 
Great suggestion! `qf_options` must contain the following parameters in start_clipper.
* cache_size
* http_thread_pool_size
* http_timeout_request
* http_timeout_content
* num_replicas (renamed from num_frontend_replicas)

**Comment by withsmilo** [comment]
@simon-mo, @dcrankshaw : 
How about this?
```python
def start_clipper(self,
                      query_frontend_image,
                      mgmt_frontend_image,
                      frontend_exporter_image,
                      cache_size,
                      num_frontend_replicas,
                      qf_http_options=None):

    # qf_http_options: (dict) extra http configuration parameters for query frontend

    default_qf_http_options = {
        "http_thread_pool_size" : 1,
        "http_timeout_request" : 5,
        "http_timeout_content" : 300
    }

    if qf_http_options is not None and type(qf_http_options) is dict:
        default_qf_http_options.update(qf_http_options)
```

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
Jenkins test this please

**Comment by withsmilo** [comment]
Jenkins ok to test

**Comment by withsmilo** [comment]
Jenkins test this please

**Review by simon-mo — APPROVED** [review]

**Pull request merged**
