### PR TITLE
Clean up the versioned model's batch_size and metrics when deleting it

### PR DESCRIPTION
**Pull request by withsmilo**
* related issue : https://github.com/ucbrise/clipper/issues/468

### CODE REVIEW

**Review by rkooo567 — DISMISSED** [review]
Looks good to me!

**Comment by withsmilo** [comment]
@rkooo567 Wait. I will push one more commit to this PR.

**Comment by withsmilo** [comment]
jenkins test this please

**Review by rkooo567 — APPROVED** [review]
LGTM!!

**Pull request merged**
