### PR TITLE
Add Python 3 support for the remaining model deployers

### PR DESCRIPTION
**Pull request by dcrankshaw**

### CODE REVIEW

**Comment by simon-mo** [comment]
jenkins test this please

**Comment by simon-mo** [comment]
jenkins test this please

**Comment by simon-mo** [comment]
I finally figured out the error. 

Out of all our integration test, only `deploy_pyspark_pipeline_models.py` register application with `strings` type. 

In python3, the following in rpc.py won't work because splitting a string with null terminator requires the string to be byte string. `raw_content` comes from `socket.recv()` which is bytes in python2 but undetermined behavior in python3:

```python
                        if input_type == INPUT_TYPE_STRINGS:
                            # If we're processing string inputs, we delimit them using
                            # the null terminator included in their serialized representation,
                            # ignoring the extraneous final null terminator by
                            # using a -1 slice
                            inputs = np.array(
                                raw_content.split('\0')[:-1],
                                dtype=input_type_to_dtype(input_type))
```

zmq:
```
The important consideration for send/recv and set/getsockopt is that when you put in something, you really should get the same object back with its partner method.
```

Due to the undefined behavior from the input side (and time limit), what we can do is just if it's a unicode string, convert it to bytes vis `.encode` method

**Comment by simon-mo** [comment]
@dcrankshaw Jenkins is timing out because our tests take more than 3 hours. Should we increase the limit or refactor our test somehow?

**Comment by dcrankshaw** [comment]
We should refactor the tests, but in the meantime I just increased the timeout threshold to 4 hours.

**Comment by simon-mo** [comment]
jenkins test this please

**Comment by simon-mo** [comment]
```
Starting PySparkContainer container
Connecting to Clipper with default port: 7000
/model
Initializing PySpark function container
2018-05-24 02:59:44 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
2018-05-24 02:59:48 WARN  SparkContext:66 - Using an existing SparkContext; some configuration may not take effect.
/usr/local/lib/python3.5/runpy.py:125: RuntimeWarning: 'clipper_admin.metrics.server' found in sys.modules after import of package 'clipper_admin.metrics', but prior to execution of 'clipper_admin.metrics.server'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
18-05-24:02:59:53 INFO     [server.py:80] Metric Server Started!
18-05-24:02:59:53 INFO     [server.py:85] Redis Connected! Waiting for messages...
Loading pyspark.ml.pipeline.PipelineModel model from /model/pyspark_model_data
Serving predictions for string input type.
Sent heartbeat!
Received heartbeat!
Sent container metadata!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Sent heartbeat!
Received heartbeat!
Got start of message 0
Traceback (most recent call last):
  File "/container/pyspark_container.py", line 137, in <module>
    input_type)
  File "/container/rpc.py", line 550, in start
    self.server.run(collect_metrics=self.collect_metrics)
  File "/container/rpc.py", line 309, in run
    raw_content.split(delimiter)[:-1],
TypeError: a bytes-like object is required, not 'str'
Encountered error not related to missing packages. Please refer to the container log to diagnose.
```
hmmm. thought 7e49f66 fixed that. 

ok found a bug. will fix soon

**Comment by simon-mo** [comment]
kubernetes test passes on my dev server. jenkins test this please

**Comment by simon-mo** [comment]
Corey's `rpc.py` re-write seems to solve the strings type issue. `deploy_pyspark_pipeline.py` now passes locally.

**Comment by dcrankshaw** [comment]
jenkins test this please

**Comment by dcrankshaw** [comment]
jenkins test this please

**Comment by dcrankshaw** [comment]
jenkins test this please

**Comment by dcrankshaw** [comment]
jenkins test this please

**Review by simon-mo — APPROVED** [review]
lgtm

**Pull request merged**
