### PR TITLE
Fix docker version to be greater than 3.0

### PR DESCRIPTION
**Pull request by RehanSD**
Docker versions less than 3.0 aren't adequate to properly run clipper.

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
lgtm

**Comment by simon-mo** [comment]
jenkins add to whitelist

**Comment by simon-mo** [comment]
jenkins ok to test

**Comment by RehanSD** [comment]
jenkins test this please

**Comment by RehanSD** [comment]
jenkins retest this please

**Pull request merged**
